on: push
name: Build and deploy GH Pages (Zola)
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
      - name: clear-err
        run: git config --global --add safe.directory /github/workspace
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@70a101a14bbdeed13e7a42a9ed06b35c9e9e826e
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # if publishing to the same repo, use the automatic token
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
